# Generated by Django 3.1.7 on 2021-03-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_citie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='citie',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
