# Generated by Django 3.1.7 on 2021-03-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citie',
            options={'verbose_name': 'citie', 'verbose_name_plural': 'cities'},
        ),
    ]
