# Generated by Django 3.1.7 on 2021-03-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0008_auto_20210326_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='alimentacao',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='extra',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hospedagem',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passagem',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
