# Generated by Django 3.1.7 on 2021-03-27 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0009_auto_20210326_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initial', models.DateField()),
                ('date_end', models.DateField()),
                ('money_end', models.DecimalField(decimal_places=2, max_digits=9)),
                ('num_months', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.trip')),
            ],
            options={
                'verbose_name': 'Resumo',
                'verbose_name_plural': 'Resumos',
            },
        ),
    ]
