# Generated by Django 3.1.7 on 2021-03-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0010_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='money_end',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
