# Generated by Django 3.1.7 on 2021-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0011_auto_20210327_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='money_month',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
