# Generated by Django 3.1.7 on 2021-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0014_auto_20210327_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumo',
            old_name='date_initial',
            new_name='date',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='remaining_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
