# Generated by Django 3.1.7 on 2021-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0015_auto_20210328_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='percent',
            field=models.FloatField(null=True),
        ),
    ]
