# Generated by Django 3.1.7 on 2021-03-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0018_auto_20210328_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumodate',
            old_name='date_initial',
            new_name='trip_date',
        ),
        migrations.AddField(
            model_name='resumodate',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
