# Generated by Django 3.1.7 on 2021-03-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0019_auto_20210328_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumodate',
            old_name='date_end',
            new_name='date',
        ),
    ]
