# Generated by Django 3.1.7 on 2021-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0021_auto_20210328_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumodate',
            name='money_month',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
